# _config.yml
title: CirQuant
description: Documentation
url: "https://equicirco.github.io/cirquant"
baseurl: "https://github.com/equicirco/cirquant"   # or "" for a user/org site

remote_theme: just-the-docs/just-the-docs@v0.10.1

plugins:
  - jekyll-remote-theme
